# NumPy Exercises

![Namespace Labs](../../../labs.png)

In [2]:
import numpy as np

In [5]:
# Create a NumPy array called mat four by four matrix from 33 to 49
mat = np.arange(33,49).reshape(4,4)
mat

array([[33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [6]:
# Display the position of the max item in mat
np.argmax(mat)

15

In [7]:
# Display the position of the min item in mat
np.argmin(mat)

0

In [8]:
# Display the  max item in mat
np.max(mat)

48

In [9]:
# Display the  min item in mat
np.min(mat)

33

In [11]:
# create a four by four array called mat2 from 49 to 65
mat2 = np.arange(49,65).reshape(4,4)
mat2

array([[49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [12]:
#add mat and mat2
mat + mat2

array([[ 82,  84,  86,  88],
       [ 90,  92,  94,  96],
       [ 98, 100, 102, 104],
       [106, 108, 110, 112]])

In [13]:
#Multiply mat and mat2
mat * mat2

array([[1617, 1700, 1785, 1872],
       [1961, 2052, 2145, 2240],
       [2337, 2436, 2537, 2640],
       [2745, 2852, 2961, 3072]])

In [14]:
#Substract mat and mat2
mat - mat2

array([[-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16]])

In [15]:
# Find the modulus of  mat and mat2
mat % mat2

array([[33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [16]:
mat

array([[33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [17]:
mat[0]

array([33, 34, 35, 36])

In [18]:
mat[0:2, 0:2]

array([[33, 34],
       [37, 38]])

In [19]:
mat[2:,1:3]

array([[42, 43],
       [46, 47]])

In [20]:
mat[1:3,1:]

array([[38, 39, 40],
       [42, 43, 44]])

In [21]:
mat

array([[33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [22]:
# Clip all the items in mat to be between 30 and 40
np.clip(mat, 30,40)

array([[33, 34, 35, 36],
       [37, 38, 39, 40],
       [40, 40, 40, 40],
       [40, 40, 40, 40]])

In [25]:
# Create an array that shows the ouptut below
np.linspace(10,20,50)
#np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [26]:
# Flatten the mat array
mat.flatten()

array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [27]:
# Find the sum of the mat array
np.sum(mat)

648

In [28]:
# Check for values greater than 35 in mat
mat > 35

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
# Print the values greater than 35
mat[mat > 35]

array([36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

Happy Coding!